import { Movie, Category } from '../models/movie';

export const movies: Movie[] = [
    {
        id: '1',
        title: 'Barbie',
        date: 1742592000000,
        desc: 'Barbie and Ken are having the time of their lives in the colorful and...',
        image: require('../../assets/barbie.png'),
        category: Category.NOW_PLAYING,
        rating: 1,
    },
    {
        id: '2',
        title: 'The Flash',
        date: 1742505600000,
        desc: 'When his attempt to save his family inadvertently alters the future, Barr...',
        image: require('../../assets/the-flash.png'),
        category: Category.POPULAR,
        rating: 5,
    },
    {
        id: '3',
        title: 'The Little Mermaid',
        date: 1742419200000,
        desc: 'The youngest of King Triton’s daughters, and the most defiant...',
        image: require('../../assets/the-little-mermaid.png'),
        category: Category.UP_COMING,
        rating: 1,
    },
    {
        id: '4',
        title: 'Barbie',
        date: 1742592000000,
        desc: 'Barbie and Ken are having the time of their lives in the colorful and...',
        image: require('../../assets/barbie.png'),
        category: Category.NOW_PLAYING,
        rating: 1,
    },
    {
        id: '5',
        title: 'Barry Allen',
        date: 1742505600000,
        desc: 'When his attempt to save his family inadvertently alters the future, Barr...',
        image: require('../../assets/the-flash.png'),
        category: Category.POPULAR,
        rating: 3,
    },
    {
        id: '6',
        title: 'The Little Mermaid',
        date: 1742419200000,
        desc: 'The youngest of King Triton’s daughters, and the most defiant...',
        image: require('../../assets/the-little-mermaid.png'),
        category: Category.UP_COMING,
        rating: 1,
    },
    {
        id: '7',
        title: 'Barbie',
        date: 1742592000000,
        desc: 'Barbie and Ken are having the time of their lives in the colorful and...',
        image: require('../../assets/barbie.png'),
        category: Category.NOW_PLAYING,
        rating: 1,
    },
    {
        id: '8',
        title: 'The hell',
        date: 1742505600000,
        desc: 'When his attempt to save his family inadvertently alters the future, Barr...',
        image: require('../../assets/the-flash.png'),
        category: Category.POPULAR,
        rating: 1,
    },
    {
        id: '9',
        title: 'The Little Mermaid',
        date: 1742419200000,
        desc: 'The youngest of King Triton’s daughters, and the most defiant...',
        image: require('../../assets/the-little-mermaid.png'),
        category: Category.UP_COMING,
        rating: 1,
    },
    {
        id: '10',
        title: 'Barbie',
        date: 1742592000000,
        desc: 'Barbie and Ken are having the time of their lives in the colorful and...',
        image: require('../../assets/barbie.png'),
        category: Category.NOW_PLAYING,
        rating: 1,
    },
    {
        id: '11',
        title: 'The Flash',
        date: 1742505600000,
        desc: 'When his attempt to save his family inadvertently alters the future, Barr...',
        image: require('../../assets/the-flash.png'),
        category: Category.POPULAR,
        rating: 4,
    },
    {
        id: '12',
        title: 'The Little Mermaid',
        date: 1742419200000,
        desc: 'The youngest of King Triton’s daughters, and the most defiant...',
        image: require('../../assets/the-little-mermaid.png'),
        category: Category.UP_COMING,
        rating: 1,
    },
    {
        id: '13',
        title: 'Barbie',
        date: 1742592000000,
        desc: 'Barbie and Ken are having the time of their lives in the colorful and...',
        image: require('../../assets/barbie.png'),
        category: Category.NOW_PLAYING,
        rating: 1,
    },
    {
        id: '14',
        title: 'Barbie',
        date: 1742592000000,
        desc: 'Barbie and Ken are having the time of their lives in the colorful and...',
        image: require('../../assets/barbie.png'),
        category: Category.NOW_PLAYING,
        rating: 1,
    },
    {
        id: '15',
        title: 'Barbie',
        date: 1742592000000,
        desc: 'Barbie and Ken are having the time of their lives in the colorful and...',
        image: require('../../assets/barbie.png'),
        category: Category.NOW_PLAYING,
        rating: 1,
    },
    {
        id: '16',
        title: 'Barbie',
        date: 1742592000000,
        desc: 'Barbie and Ken are having the time of their lives in the colorful and...',
        image: require('../../assets/barbie.png'),
        category: Category.NOW_PLAYING,
        rating: 1,
    },
    {
        id: '17',
        title: 'The Little Mermaid',
        date: 1742419200000,
        desc: 'The youngest of King Triton’s daughters, and the most defiant...',
        image: require('../../assets/the-little-mermaid.png'),
        category: Category.UP_COMING,
        rating: 1,
    },
];
