import { Category } from '@models/movie';

export const movies = [
    {
        id: 'movie-1',
        title: 'Movie 1',
        date: 1705017600000,
        desc: 'Movie 1 is an unforgettable cinematic experience.',
        image: require('@assets/the-little-mermaid.png'),
        category: Category.POPULAR,
        rating: 9.3,
        releaseDate: 1705017600000,
        duration: 5900000,
        ratingMPAA: 'PG13',
        status: 'Released',
        originalLanguage: 'English',
        genres: ['Comedy', 'Horror', 'Thriller'],
        overview: 'Movie 1 is a thrilling journey that captures the imagination and leaves a lasting impact.',
        shortDesc: 'A short description of Movie 1.',
        tagline: 'This is the story of Movie 1.',
        posterUrl: 'https://example.com/movie1.jpg',
        userScore: 84,
        crew: [
            {
                name: 'Robert Lee',
                roles: ['Director', 'Writer'],
            },
            {
                name: 'James Brown',
                roles: ['Writer'],
            },
        ],
    },
    {
        id: 'movie-2',
        title: 'Movie 2',
        date: 1689552000000,
        desc: 'Movie 2 is an unforgettable cinematic experience.',
        image: require('@assets/barbie.png'),
        category: Category.POPULAR,
        rating: 8.6,
        releaseDate: 1689552000000,
        duration: 5700000,
        ratingMPAA: 'R',
        status: 'Released',
        originalLanguage: 'English',
        genres: ['Fantasy', 'Thriller', 'Romance'],
        overview: 'Movie 2 is a thrilling journey that captures the imagination and leaves a lasting impact.',
        shortDesc: 'A short description of Movie 2.',
        tagline: 'This is the story of Movie 2.',
        posterUrl: 'https://example.com/movie2.jpg',
        userScore: 78,
        crew: [
            {
                name: 'James Brown',
                roles: ['Director', 'Writer'],
            },
            {
                name: 'Jane Doe',
                roles: ['Writer'],
            },
        ],
    },
    {
        id: 'movie-3',
        title: 'Movie 3',
        date: 1650672000000,
        desc: 'Movie 3 is an unforgettable cinematic experience.',
        image: require('@assets/the-flash.png'),
        category: Category.POPULAR,
        rating: 8.7,
        releaseDate: 1650672000000,
        duration: 5700000,
        ratingMPAA: 'PG',
        status: 'Released',
        originalLanguage: 'English',
        genres: ['Horror', 'Adventure', 'Action'],
        overview: 'Movie 3 is a thrilling journey that captures the imagination and leaves a lasting impact.',
        shortDesc: 'A short description of Movie 3.',
        tagline: 'This is the story of Movie 3.',
        posterUrl: 'https://example.com/movie3.jpg',
        userScore: 88,
        crew: [
            {
                name: 'Sofia Rossi',
                roles: ['Director', 'Writer'],
            },
            {
                name: 'Sofia Rossi',
                roles: ['Writer'],
            },
        ],
    },
    {
        id: 'movie-4',
        title: 'Movie 4',
        date: 1673136000000,
        desc: 'Movie 4 is an unforgettable cinematic experience.',
        image: require('@assets/the-flash.png'),
        category: Category.POPULAR,
        rating: 6.7,
        releaseDate: 1673136000000,
        duration: 5700000,
        ratingMPAA: 'R',
        status: 'Released',
        originalLanguage: 'English',
        genres: ['Thriller', 'Drama', 'Action'],
        overview: 'Movie 4 is a thrilling journey that captures the imagination and leaves a lasting impact.',
        shortDesc: 'A short description of Movie 4.',
        tagline: 'This is the story of Movie 4.',
        posterUrl: 'https://example.com/movie4.jpg',
        userScore: 66,
        crew: [
            {
                name: 'Sofia Rossi',
                roles: ['Director', 'Writer'],
            },
            {
                name: 'Robert Lee',
                roles: ['Writer'],
            },
        ],
    },
    {
        id: 'movie-5',
        title: 'Movie 5',
        date: 1647907200000,
        desc: 'Movie 5 is an unforgettable cinematic experience.',
        image: require('@assets/barbie.png'),
        category: Category.UP_COMING,
        rating: 7.4,
        releaseDate: 1647907200000,
        duration: 5700000,
        ratingMPAA: 'PG',
        status: 'Released',
        originalLanguage: 'English',
        genres: ['Action', 'Comedy', 'Thriller'],
        overview: 'Movie 5 is a thrilling journey that captures the imagination and leaves a lasting impact.',
        shortDesc: 'A short description of Movie 5.',
        tagline: 'This is the story of Movie 5.',
        posterUrl: 'https://example.com/movie5.jpg',
        userScore: 67,
        crew: [
            {
                name: 'James Brown',
                roles: ['Director', 'Writer'],
            },
            {
                name: 'Emily Zhang',
                roles: ['Writer'],
            },
        ],
    },
    {
        id: 'movie-6',
        title: 'Movie 6',
        date: 1662768000000,
        desc: 'Movie 6 is an unforgettable cinematic experience.',
        image: require('@assets/guardians-of-the-galaxy-3.png'),
        category: Category.NOW_PLAYING,
        rating: 7.3,
        releaseDate: 1662768000000,
        duration: 6800000,
        ratingMPAA: 'R',
        status: 'Released',
        originalLanguage: 'English',
        genres: ['Horror', 'Action', 'Sci-Fi'],
        overview: 'Movie 6 is a thrilling journey that captures the imagination and leaves a lasting impact.',
        shortDesc: 'A short description of Movie 6.',
        tagline: 'This is the story of Movie 6.',
        posterUrl: 'https://example.com/movie6.jpg',
        userScore: 90,
        crew: [
            {
                name: 'Sofia Rossi',
                roles: ['Director', 'Writer'],
            },
            {
                name: 'Emily Zhang',
                roles: ['Writer'],
            },
        ],
        topBilledCast: [
            {
                image: require('@assets/actor.png'),
                name: 'Ryan Gosling',
                characterName: 'Ken',
            },
            {
                image: require('@assets/female-actor.png'),
                name: 'Margot Robbie',
                characterName: 'Barbie',
            },
        ],
    },
    {
        id: 'movie-7',
        title: 'Movie 7',
        date: 1665360000000,
        desc: 'Movie 7 is an unforgettable cinematic experience.',
        image: require('@assets/the-flash.png'),
        category: Category.NOW_PLAYING,
        rating: 9.5,
        releaseDate: 1665360000000,
        duration: 5700000,
        ratingMPAA: 'PG',
        status: 'Released',
        originalLanguage: 'English',
        genres: ['Fantasy', 'Sci-Fi', 'Comedy'],
        overview: 'Movie 7 is a thrilling journey that captures the imagination and leaves a lasting impact.',
        shortDesc: 'A short description of Movie 7.',
        tagline: 'This is the story of Movie 7.',
        posterUrl: 'https://example.com/movie7.jpg',
        userScore: 89,
        crew: [
            {
                name: 'Sofia Rossi',
                roles: ['Director', 'Writer'],
            },
            {
                name: 'Jane Doe',
                roles: ['Writer'],
            },
        ],
    },
    {
        id: 'movie-8',
        title: 'Movie 8',
        date: 1700784000000,
        desc: 'Movie 8 is an unforgettable cinematic experience.',
        image: require('@assets/the-flash.png'),
        category: Category.UP_COMING,
        rating: 7.4,
        releaseDate: 1700784000000,
        duration: 5700000,
        ratingMPAA: 'PG',
        status: 'Released',
        originalLanguage: 'English',
        genres: ['Comedy', 'Action', 'Fantasy'],
        overview: 'Movie 8 is a thrilling journey that captures the imagination and leaves a lasting impact.',
        shortDesc: 'A short description of Movie 8.',
        tagline: 'This is the story of Movie 8.',
        posterUrl: 'https://example.com/movie8.jpg',
        userScore: 69,
        crew: [
            {
                name: 'Chris Johnson',
                roles: ['Director', 'Writer'],
            },
            {
                name: 'James Brown',
                roles: ['Writer'],
            },
        ],
    },
    {
        id: 'movie-9',
        title: 'Movie 9',
        date: 1678060800000,
        desc: 'Movie 9 is an unforgettable cinematic experience.',
        image: require('@assets/the-flash.png'),
        category: Category.UP_COMING,
        rating: 8.2,
        releaseDate: 1678060800000,
        duration: 5700000,
        ratingMPAA: 'G',
        status: 'Released',
        originalLanguage: 'English',
        genres: ['Romance', 'Sci-Fi', 'Drama'],
        overview: 'Movie 9 is a thrilling journey that captures the imagination and leaves a lasting impact.',
        shortDesc: 'A short description of Movie 9.',
        tagline: 'This is the story of Movie 9.',
        posterUrl: 'https://example.com/movie9.jpg',
        userScore: 88,
        crew: [
            {
                name: 'Chris Johnson',
                roles: ['Director', 'Writer'],
            },
            {
                name: 'Anna Kim',
                roles: ['Writer'],
            },
        ],
    },
    {
        id: 'movie-10',
        title: 'Movie 10',
        date: 1642636800000,
        desc: 'Movie 10 is an unforgettable cinematic experience.',
        image: require('@assets/the-flash.png'),
        category: Category.POPULAR,
        rating: 8.1,
        releaseDate: 1642636800000,
        duration: 5700000,
        ratingMPAA: 'PG13',
        status: 'Released',
        originalLanguage: 'English',
        genres: ['Fantasy', 'Comedy', 'Thriller'],
        overview: 'Movie 10 is a thrilling journey that captures the imagination and leaves a lasting impact.',
        shortDesc: 'A short description of Movie 10.',
        tagline: 'This is the story of Movie 10.',
        posterUrl: 'https://example.com/movie10.jpg',
        userScore: 73,
        crew: [
            {
                name: 'Emily Zhang',
                roles: ['Director', 'Writer'],
            },
            {
                name: 'Jane Doe',
                roles: ['Writer'],
            },
        ],
    },
    {
        id: 'movie-11',
        title: 'Movie 11',
        date: 1669593600000,
        desc: 'Movie 11 is an unforgettable cinematic experience.',
        image: require('@assets/the-flash.png'),
        category: Category.UP_COMING,
        rating: 8.1,
        releaseDate: 1669593600000,
        duration: 5700000,
        ratingMPAA: 'G',
        status: 'Released',
        originalLanguage: 'English',
        genres: ['Adventure', 'Sci-Fi', 'Comedy'],
        overview: 'Movie 11 is a thrilling journey that captures the imagination and leaves a lasting impact.',
        shortDesc: 'A short description of Movie 11.',
        tagline: 'This is the story of Movie 11.',
        posterUrl: 'https://example.com/movie11.jpg',
        userScore: 76,
        crew: [
            {
                name: 'John Smith',
                roles: ['Director', 'Writer'],
            },
            {
                name: 'Robert Lee',
                roles: ['Writer'],
            },
        ],
    },
    {
        id: 'movie-12',
        title: 'Movie 12',
        date: 1653609600000,
        desc: 'Movie 12 is an unforgettable cinematic experience.',
        image: require('@assets/the-flash.png'),
        category: Category.UP_COMING,
        rating: 8.1,
        releaseDate: 1653609600000,
        duration: 5700000,
        ratingMPAA: 'R',
        status: 'Released',
        originalLanguage: 'English',
        genres: ['Thriller', 'Action', 'Romance'],
        overview: 'Movie 12 is a thrilling journey that captures the imagination and leaves a lasting impact.',
        shortDesc: 'A short description of Movie 12.',
        tagline: 'This is the story of Movie 12.',
        posterUrl: 'https://example.com/movie12.jpg',
        userScore: 68,
        crew: [
            {
                name: 'Robert Lee',
                roles: ['Director', 'Writer'],
            },
            {
                name: 'Chris Johnson',
                roles: ['Writer'],
            },
        ],
    },
    {
        id: 'movie-13',
        title: 'Movie 13',
        date: 1680998400000,
        desc: 'Movie 13 is an unforgettable cinematic experience.',
        image: require('@assets/the-flash.png'),
        category: Category.POPULAR,
        rating: 8.4,
        releaseDate: 1680998400000,
        duration: 570000,
        ratingMPAA: 'PG',
        status: 'Released',
        originalLanguage: 'English',
        genres: ['Sci-Fi', 'Adventure', 'Action'],
        overview: 'Movie 13 is a thrilling journey that captures the imagination and leaves a lasting impact.',
        shortDesc: 'A short description of Movie 13.',
        tagline: 'This is the story of Movie 13.',
        posterUrl: 'https://example.com/movie13.jpg',
        userScore: 73,
        crew: [
            {
                name: 'Jane Doe',
                roles: ['Director', 'Writer'],
            },
            {
                name: 'Anna Kim',
                roles: ['Writer'],
            },
        ],
    },
    {
        id: 'movie-14',
        title: 'Movie 14',
        date: 1644796800000,
        desc: 'Movie 14 is an unforgettable cinematic experience.',
        image: require('@assets/the-flash.png'),
        category: Category.POPULAR,
        rating: 6.2,
        releaseDate: 1644796800000,
        duration: 570000,
        ratingMPAA: 'G',
        status: 'Released',
        originalLanguage: 'English',
        genres: ['Romance', 'Fantasy', 'Action'],
        overview: 'Movie 14 is a thrilling journey that captures the imagination and leaves a lasting impact.',
        shortDesc: 'A short description of Movie 14.',
        tagline: 'This is the story of Movie 14.',
        posterUrl: 'https://example.com/movie14.jpg',
        userScore: 80,
        crew: [
            {
                name: 'Chris Johnson',
                roles: ['Director', 'Writer'],
            },
            {
                name: 'Anna Kim',
                roles: ['Writer'],
            },
        ],
    },
    {
        id: 'movie-15',
        title: 'Movie 15',
        date: 1707609600000,
        desc: 'Movie 15 is an unforgettable cinematic experience.',
        image: require('@assets/the-flash.png'),
        category: Category.POPULAR,
        rating: 6.7,
        releaseDate: 1707609600000,
        duration: 5700000,
        ratingMPAA: 'R',
        status: 'Released',
        originalLanguage: 'English',
        genres: ['Sci-Fi', 'Fantasy', 'Drama'],
        overview: 'Movie 15 is a thrilling journey that captures the imagination and leaves a lasting impact.',
        shortDesc: 'A short description of Movie 15.',
        tagline: 'This is the story of Movie 15.',
        posterUrl: 'https://example.com/movie15.jpg',
        userScore: 95,
        crew: [
            {
                name: 'Jane Doe',
                roles: ['Director', 'Writer'],
            },
            {
                name: 'Emily Zhang',
                roles: ['Writer'],
            },
        ],
    },
    {
        id: 'movie-16',
        title: 'Movie 16',
        date: 1645660800000,
        desc: 'Movie 16 is an unforgettable cinematic experience.',
        image: require('@assets/the-flash.png'),
        category: Category.POPULAR,
        rating: 9.0,
        releaseDate: 1645660800000,
        duration: 5700000,
        ratingMPAA: 'PG',
        status: 'Released',
        originalLanguage: 'English',
        genres: ['Adventure', 'Horror', 'Action'],
        overview: 'Movie 16 is a thrilling journey that captures the imagination and leaves a lasting impact.',
        shortDesc: 'A short description of Movie 16.',
        tagline: 'This is the story of Movie 16.',
        posterUrl: 'https://example.com/movie16.jpg',
        userScore: 61,
        crew: [
            {
                name: 'Jane Doe',
                roles: ['Director', 'Writer'],
            },
            {
                name: 'James Brown',
                roles: ['Writer'],
            },
        ],
    },
    {
        id: 'movie-17',
        title: 'Movie 17',
        date: 1678665600000,
        desc: 'Movie 17 is an unforgettable cinematic experience.',
        image: require('@assets/the-flash.png'),
        category: Category.NOW_PLAYING,
        rating: 8.1,
        releaseDate: 1678665600000,
        duration: 5700000,
        ratingMPAA: 'G',
        status: 'Released',
        originalLanguage: 'English',
        genres: ['Comedy', 'Adventure', 'Thriller'],
        overview: 'Movie 17 is a thrilling journey that captures the imagination and leaves a lasting impact.',
        shortDesc: 'A short description of Movie 17.',
        tagline: 'This is the story of Movie 17.',
        posterUrl: 'https://example.com/movie17.jpg',
        userScore: 78,
        crew: [
            {
                name: 'Sofia Rossi',
                roles: ['Director', 'Writer'],
            },
            {
                name: 'Robert Lee',
                roles: ['Writer'],
            },
        ],
    },
    {
        id: 'movie-18',
        title: 'Movie 18',
        date: 1663200000000,
        desc: 'Movie 18 is an unforgettable cinematic experience.',
        image: require('@assets/the-flash.png'),
        category: Category.NOW_PLAYING,
        rating: 8.1,
        releaseDate: 1663200000000,
        duration: 5700000,
        ratingMPAA: 'PG',
        status: 'Released',
        originalLanguage: 'English',
        genres: ['Adventure', 'Comedy', 'Action'],
        overview: 'Movie 18 is a thrilling journey that captures the imagination and leaves a lasting impact.',
        shortDesc: 'A short description of Movie 18.',
        tagline: 'This is the story of Movie 18.',
        posterUrl: 'https://example.com/movie18.jpg',
        userScore: 86,
        crew: [
            {
                name: 'Sofia Rossi',
                roles: ['Director', 'Writer'],
            },
            {
                name: 'Chris Johnson',
                roles: ['Writer'],
            },
        ],
        topBilledCast: [
            {
                image: require('@assets/actor.png'),
                name: 'Ryan Gosling',
                characterName: 'Ken',
            },
            {
                image: require('@assets/female-actor.png'),
                name: 'Margot Robbie',
                characterName: 'Barbie',
            },
        ],
    },
    {
        id: 'movie-19',
        title: 'Movie 19',
        date: 1674691200000,
        desc: 'Movie 19 is an unforgettable cinematic experience.',
        image: require('@assets/the-flash.png'),
        category: Category.NOW_PLAYING,
        rating: 6.3,
        releaseDate: 1674691200000,
        duration: 5700000,
        ratingMPAA: 'PG13',
        status: 'Released',
        originalLanguage: 'English',
        genres: ['Sci-Fi', 'Comedy', 'Adventure'],
        overview: 'Movie 19 is a thrilling journey that captures the imagination and leaves a lasting impact.',
        shortDesc: 'A short description of Movie 19.',
        tagline: 'This is the story of Movie 19.',
        posterUrl: 'https://example.com/movie19.jpg',
        userScore: 76,
        crew: [
            {
                name: 'Emily Zhang',
                roles: ['Director', 'Writer'],
            },
            {
                name: 'Jane Doe',
                roles: ['Writer'],
            },
        ],
    },
    {
        id: 'movie-20',
        title: 'Movie 20',
        date: 1686700800000,
        desc: 'Movie 20 is an unforgettable cinematic experience.',
        image: require('@assets/the-flash.png'),
        category: Category.UP_COMING,
        rating: 8.1,
        releaseDate: 1686700800000,
        duration: 5700000,
        ratingMPAA: 'G',
        status: 'Released',
        originalLanguage: 'English',
        genres: ['Thriller', 'Fantasy', 'Sci-Fi'],
        overview: 'Movie 20 is a thrilling journey that captures the imagination and leaves a lasting impact.',
        shortDesc: 'A short description of Movie 20.',
        tagline: 'This is the story of Movie 20.',
        posterUrl: 'https://example.com/movie20.jpg',
        userScore: 61,
        crew: [
            {
                name: 'Jane Doe',
                roles: ['Director', 'Writer'],
            },
            {
                name: 'Robert Lee',
                roles: ['Writer'],
            },
        ],
    },
];
